### ISSUE TITLE
Can you make a new release?

### ISSUE THREAD

**Issue by rgoldberg** [osimek1/intellij-code-blocks-sorter#12]
I noticed the following warning in my `idea.log` after startup:

```
WARN - nSystem.impl.ActionManagerImpl - keymap "#default" not found [Plugin: eu.osimowicz.plugins.intellij.CodeBlocksSorter]
```

You've already fixed this, but haven't yet released the fix.  Can you please make a new release?

Thanks.

**Comment by osimek1** [comment]
I will do it this week. Thank you for information I didn't notice that

**Comment by osimek1** [comment]
@rgoldberg for your innformation - we are waiting for aproval from jetbrains
